Added documentation and fixed a minor bug

diff --git a/src/dry-wit b/src/dry-wit
--- a/src/dry-wit
+++ b/src/dry-wit
@@ -233,16 +233,36 @@ function _debugEcho() {
 ## PUBLIC
 ## Checks whether given value is empty.
 ## -> 1: The value to check.
-## <- 0: if the value is empty; 1 otherwise.
+## <- 0/${TRUE} if the value is empty; 1/${FALSE} otherwise.
 ## Example:
 ##   if isEmpty "${MYVAR}"; then echo "MYVAR is empty"; fi
 function isEmpty() {
-  local _rescode;
+  local -i _rescode;
+
   if [ -z "${1}" ]; then
-    _rescode=${TRUE};
+      _rescode=${TRUE};
   else
     _rescode=${FALSE};
   fi
+
+  return ${_rescode};
+}
+
+## PUBLIC
+## Checks whether given value is not empty.
+## -> 1: The value to check.
+## <- 0/${TRUE} if the value is not empty; 1/${FALSE} otherwise.
+## Example:
+##   if isNotEmpty "${MYVAR}"; then echo "MYVAR is not empty"; fi
+function isNotEmpty() {
+  local -i _rescode;
+
+  if isEmpty "${1}"; then
+      _rescode=${FALSE};
+  else
+    _rescode=${TRUE};
+  fi
+
   return ${_rescode};
 }
 
@@ -649,21 +669,31 @@ function cleanup() {
     local _oldIFS="${IFS}";
     IFS=$' \t\n';
     for i in ${_CLEANUP_FILES[*]}; do
+      IFS="${_oldIFS}";
       logTrace -n "Deleting $i";
-      rm -rf $i > /dev/null;
-      if [ $? -eq 0 ]; then
-        logTraceResult SUCCESS "${_DW_DONE}";
+      rm -rf $i > /dev/null 2>&1;
+      if isTrue $?; then
+          logTraceResult SUCCESS "${_DW_DONE}";
       else
         logTraceResult FAILURE "${_DW_FAILED}";
       fi
     done
-    IFS="${_oldIFS}";
 
     logDebugResult SUCCESS "${_DW_DONE}";
   fi
 }
 
+## Creates a new temporary file.
+## <- 0/${TRUE} if the file gets created successfully; 1/${FALSE} otherwise.
+## <- RESULT: The name of the temporary file.
+## Example:
+##   if createTempFile; then
+##     echo "Temp file: ${RESULT}";
+##   fi
 function createTempFile() {
+  local -i _rescode;
+  local _result;
+
   local _prefix="$(echo \"${SCRIPT_NAME}\" | awk -F"/" '{print $NF;}' | sed 's/^"//g' | sed 's/"$//g')";
   local _dirname="$(dirname \"${SCRIPT_NAME}\")";
 #  local _prefix="$(echo "${SCRIPT_NAME}" | awk -F"/" '{print $NF;}')";
@@ -673,19 +703,18 @@ function createTempFile() {
   else
     _dirname="$PWD/../${_dirname#\.\.}";
   fi
-  local _result="$(mktemp -p "${_dirname}"  -t ".${_prefix}.XXXXXXXXXX")";
-  local _aux=$?;
-  rm -f ${_result} > /dev/null
-  if isFalse ${_aux} ; then
+  _result="$(mktemp -p "${_dirname}"  -t ".${_prefix}.XXXXXXXXXX")";
+  _rescode=$?;
+  rm -f ${_result} > /dev/null 2>&1
+  if isFalse ${_rescode} ; then
      _result="$(mktemp -t ".${_prefix}.XXXXXXXXXX")";
-     _aux=$?;
-  fi
-  if [ $_aux -ne 0 ]; then
-     exitWithErrorCode $1;
+     _rescode=$?;
   fi
   addFileToCleanup "${_result}";
 
-  export RESULT="${_result}";
+  if isTrue ${_rescode}; then
+      export RESULT="${_result}";
+  fi
 }
 
 ## Checks if given file is writeable
@@ -743,6 +772,10 @@ function appendEnvVariable() {
   fi
 }
 
+## Annotates a file to be removed.
+## -> 1: The file to delete.
+## Example:
+##   addFileToCleanup "/tmp/my-log.txt";
 function addFileToCleanup() {
   local _file="${1}";
   #  logTrace "Appending ${result} to _CLEANUP_FILES";
@@ -753,7 +786,7 @@ function addFileToCleanup() {
   else
     export -a _CLEANUP_FILES=();
     upvars -a1 _CLEANUP_FILES "${_file}";
-    export _CREANUP_FILES;
+    export _CLEANUP_FILES;
   fi
 
 #  local _oldIFS="${IFS}";
@@ -765,42 +798,60 @@ function addFileToCleanup() {
 #  IFS="${_oldIFS}";
 }
 
+## Creates a temporary folder.
+## <- 0/${TRUE} if the folder gets created successfully; 1/${FALSE} otherwise.
+## <- RESULT: the new folder.
+## Example:
+##   if createTempFolder; then
+##     echo "New folder: ${RESULT}";
+##   fi
 function createTempFolder() {
+  local -i _rescode;
+  local _result;
+
   local _prefix="$(echo ${SCRIPT_NAME} | awk -F"/" '{print $NF;}')";
   local _dirname="$(dirname ${SCRIPT_NAME})";
   if [ "${_dirname#\.\.}" == "${_dirname}" ]; then
-    _dirname="$PWD/${_dirname#\.}";
+    _dirname="${PWD}/${_dirname#\.}";
   else
-    _dirname="$PWD/../${_dirname#\.\.}";
+    _dirname="${PWD}/../${_dirname#\.\.}";
   fi
-  local result=$(mktemp -p "${_dirname}" -d -t ".${_prefix}.XXXXXX");
-  local _aux=$?;
-  if isFalse $_aux; then
-    result=$(mktemp -d -t ".${_prefix}.XXXXXX");
-    _aux=$?;
+  _result=$(mktemp -p "${_dirname}" -d -t ".${_prefix}.XXXXXX");
+  _rescode=$?;
+  if isFalse ${_rescode}; then
+      _result=$(mktemp -d -t ".${_prefix}.XXXXXX");
+      _rescode=$?;
   fi
-  if isFalse $_aux; then
-     exitWithErrorCode $1;
+  addFileToCleanup "${_result}";
+  if isTrue ${_rescode}; then
+      export RESULT="${_result}";
   fi
-  addFileToCleanup "${result}";
-
-  export RESULT="${result}";
 }
 
+## Extracts the flags from the arguments.
+## -> *: The arguments to process.
+## <- [STDOUT]: the flags.
+## Example:
+##   local _myFlags=$(extractFlags $*);
 function extractFlags() {
-  local result="";
   echo " $@" \
     | awk -F" -" '{for (i=2; i<=NF; i++){printf("-%s \n", $i);}}' \
     | awk -F" " '{print $1;}'
 }
 
+## Extracts the flag value for the arguments.
+## -> 1: The flag name.
+## -> 2-*: The arguments.
+## <- [STDOUT]: the flag value.
+## Example:
+##   local _Ext=$(extractFlagValue "ext" $*);
 function extractFlagValue() {
-  local flag=$1;
+  local _flag=${1};
   shift;
   echo " $@" \
     | awk -F" -" '{printf("-"); for (i=2; i<=NF; i++){if(i%2 == 1) {printf("-");}; printf("%s \n", $i);}}' \
-    | grep -e "^$flag " \
-    | awk -v f="${flag}" '{printf("echo \"%s\" | sed -e \"s_^%s __g\"\n", $2, f);}' \
+    | grep -e "^${_flag} " \
+    | awk -v f="${_flag}" '{printf("echo \"%s\" | sed -e \"s_^%s __g\"\n", $2, f);}' \
     | sh;
 }
 
@@ -4105,3 +4156,4 @@ function uncache() {
 source $@;
 _main $@;
 cleanup;
+
