Implemented retrieveIp function

diff --git a/src/dry-wit b/src/dry-wit
--- a/src/dry-wit
+++ b/src/dry-wit
@@ -4763,6 +4763,86 @@ function uncache() {
   unset rescode_cahe["$*"]
 }
 
+# Network functions
+## Retrieves the first network interface.
+## <- RESULT: such interface name.
+## Usage:
+##   if retrieveIface; then
+##     echo "Interface candidate: ${RESULT}";
+##   fi
+function retrieveIface() {
+  local _result;
+  local -i _rescode;
+
+  logInfo -n "Finding out the name of the network interface";
+  _result="$(ifconfig | cut -d' ' -f1 | grep -v -e '^$' | tr ' ' '\n' | tr -d ':' | grep -v -e '^docker' | grep -v -e '^lo$' | grep -v -e '^tun' | head -n 1)";
+  _rescode=$?;
+  if isTrue ${_rescode}; then
+      logInfoResult SUCCESS "${_result}";
+      export RESULT="${_result}";
+  else
+    logInfoResult FAILED "failed";
+  fi
+
+  return ${_rescode};
+}
+
+## Retrieves the IP for given interface.
+## -> 1: the interface name.
+## <- 0/${TRUE} if the IP is up; 1/${FALSE} otherwise.
+## <- RESULT: The IP.
+## Example:
+##   if retrieveIp "eth0"; then
+##     echo "IP: ${RESULT}";
+##   fi
+function retrieveIp() {
+  local _iface="${1}";
+  local -i _rescode;
+  local _result;
+
+  checkNotEmpty "interface" "${_iface}" 1;
+
+  _result="$(ifconfig ${_iface} | grep 'inet ' | sed 's/ addr://g' | sed 's/inet /inet:/g' | cut -d':' -f 2 | awk '{print $1;}')";
+  _rescode=$?;
+
+  if isTrue ${_rescode}; then
+      export RESULT=${_result};
+  fi
+
+  return ${_rescode};
+}
+
+## Retrieves the /24 subnet of given network interface.
+## -> 1: The interface name.
+## <- 0/${TRUE} if the subnet information is available; 1/${FALSE} otherwise.
+## <- RESULT: the device where the root filesystem is stored.
+## Usage:
+##   if retrieveSubnet24 "eth0"; then
+##     echo "The /24 subnet for eth0 is ${RESULT}"
+##   fi
+function retrieveSubnet24() {
+  local _iface="${1}";
+  local _ip;
+  local -i rescode=${FALSE};
+  local _result;
+
+  checkNotEmpty "iface" "${_iface}" 1;
+
+  if retrieveIp "${_iface}"; then
+      _ip="${RESULT}";
+      _result="$(echo ${_ip} | awk -F'.' '{printf("%d.%d.%d.0/24\n", $1, $2, $3);}')";
+
+      if isEmpty ${_result}; then
+          rescode=${FALSE}
+      else
+        export RESULT="${_result}";
+        rescode=${TRUE};
+      fi
+  fi
+
+  return ${rescode};
+}
+
 source $@;
 _main $@;
 cleanup;
