Support for on-demand module download

diff --git a/src/dry-wit b/src/dry-wit
--- a/src/dry-wit
+++ b/src/dry-wit
@@ -33,15 +33,14 @@ fi
 declare -a __DRYWIT_BOOTSTRAP_MODULES=(\
    "stdlib" \
    "string" \
+   "color" \
    "array" \
    "check" \
    "envvar" \
    "constant" \
    "error" \
-   "envvar" \
    "term" \
    "echo" \
-   "color" \
    "logging" \
    "cli" \
    "usage" \
@@ -52,8 +51,47 @@ declare -a __DRYWIT_BOOTSTRAP_MODULES=(\
 declare -a __DRYWIT_IMPORTED_MODULES;
 
 export DRYWIT_MODULE_TAG="master";
-export DRYWIT_MODULE_URL="https://raw.githubusercontent.com/rydnr/dry-wit/master/src/${DRYWIT_MODULE_TAG}";
+export DRYWIT_MODULE_URL="https://raw.githubusercontent.com/rydnr/dry-wit/${DRYWIT_MODULE_TAG}/src/modules";
 export DRYWIT_MODULE_PATH="${HOME}/.dry-wit/modules"
+
+function DRYWIT.failsafeLogTrace() {
+  local _message="${1}";
+
+  ## Needed since this function is used in bootstrapping, and could be loaded before
+  ## checkNotEmpty is loaded.
+  type checkNotEmpty 2> /dev/null | grep -q 'function';
+  if [[ $? -eq ${TRUE} ]]; then
+    checkNotEmpty "module" "${_module}" 1;
+  fi
+
+  ## Needed since this function is used in bootstrapping, and could be loaded before
+  ## logTrace is loaded.
+  type logTrace 2> /dev/null | grep -q 'function';
+  if [[ $? -eq ${TRUE} ]]; then
+    logTrace -n "${_message}";
+  fi
+
+}
+
+function DRYWIT.failsafeLogTraceResult() {
+  local _outcome="${1}";
+  local _outcomeMessage="${2}";
+
+  ## Needed since this function is used in bootstrapping, and could be loaded before
+  ## checkNotEmpty is loaded.
+  type checkNotEmpty 2> /dev/null | grep -q 'function';
+  if [[ $? -eq ${TRUE} ]]; then
+    checkNotEmpty "outcome" "${_outcome}" 1;
+    checkNotEmpty "outcomeMessage" "${_outcomeMessage}" 2;
+  fi
+
+  ## Needed since this function is used in bootstrapping, and could be loaded before
+  ## logTraceResult is loaded.
+  type logTraceResult 2> /dev/null | grep -q 'function';
+  if [[ $? -eq ${TRUE} ]]; then
+    logTraceResult ${_outcome} "${_outcomeMessage}";
+  fi
+}
 
 function downloadModule() {
   local _module="${1}";
@@ -62,14 +100,14 @@ function downloadModule() {
 
   mkdir -p "${DRYWIT_MODULE_PATH}";
 
-  echo -n "Downloading ${_module} from ${DRYWIT_MODULE_URL}/${_module}.dw ... ";
+  DRYWIT.failsafeLogTrace "Downloading '${_module}' module from ${DRYWIT_MODULE_URL}/${_module}.dw";
   curl -s "${DRYWIT_MODULE_URL}/${_module}.dw" > "${DRYWIT_MODULE_PATH}/${_module}.dw";
   _rescode=$?;
   if [[ ${_rescode} -eq ${TRUE} ]]; then
-    echo "done";
+    DRYWIT.failsafeLogTraceResult SUCCESS "done";
     export RESULT="${DRYWIT_MODULE_PATH}/${_module}.dw";
   else
-    echo "failed";
+    DRYWIT.failsafeLogTraceResult FAILURE "failed";
   fi
 
   return ${_rescode};
@@ -80,29 +118,34 @@ function DRYWIT.bootstrap() {
   local _modulePath;
 
   for _module in ${__DRYWIT_BOOTSTRAP_MODULES[*]}; do
-    if findModule "${_module}"; then
-      _modulePath="${RESULT}";
-    elif downloadModule "${_module}"; then
-      _modulePath="${RESULT}";
-    else
-      echo "ERROR: Required module ${_module}.dw not found. Please reinstall dry-wit."
-      exit 1;
-    fi
+    import "${_module}";
   done
 
-  source "${_modulePath}";
-  __DRYWIT_IMPORTED_MODULES[${#__DRYWIT_IMPORTED_MODULES[@]}]="${_module}";
 }
 
 function import() {
   local _module="${1}";
 
-  if findModule "${_module}"; then
-    source ${RESULT};
-    if arrayDoesNotContain "${__DRYWIT_IMPORTED_MODULES[@]}" "${_module}"; then
-      __DRYWIT_IMPORTED_MODULES[${#__DRYWIT_IMPORTED_MODULES}]="${_module}";
-    fi
+  ## Needed since this function is used in bootstrapping, and could be loaded before
+  ## checkNotEmpty is loaded.
+  type checkNotEmpty 2> /dev/null | grep -q 'function';
+  if [[ $? -eq ${TRUE} ]]; then
+    checkNotEmpty "module" "${_module}" 1;
   fi
+
+  if findModule "${_module}"; then
+    _modulePath="${RESULT}";
+  elif downloadModule "${_module}"; then
+    _modulePath="${RESULT}";
+  else
+    echo "ERROR: Required module ${_module}.dw not found. Is it correctly spelled?"
+    exit 1;
+  fi
+
+  DRYWIT.failsafeLogTrace "Loading ${_modulePath}";
+  source "${_modulePath}";
+  DRYWIT.failsafeLogTraceResult SUCCESS "done";
+  __DRYWIT_IMPORTED_MODULES[${#__DRYWIT_IMPORTED_MODULES[@]}]="${_module}";
 }
 
 function findModule() {
@@ -111,13 +154,10 @@ function findModule() {
   local _folder;
   local _result="";
 
-  for _folder in ${HOME}/.dry-wit $(dirname $(which dry-wit)) /usr/share/dry-wit; do
-    if [[ -e "${_folder}"/"${_module}.dw" ]]; then
-      _rescode=${TRUE};
-      _result="${_folder}/${_module}.dw";
-      break;
-    fi
-  done
+  if [[ -e "${DRYWIT_MODULE_PATH}/${_module}.dw" ]]; then
+    _rescode=${TRUE};
+    _result="${DRYWIT_MODULE_PATH}/${_module}.dw";
+  fi
 
   export RESULT="${_result}";
 
