Fixed an infinite loop in isFunctionDefined

diff --git a/src/dry-wit b/src/dry-wit
--- a/src/dry-wit
+++ b/src/dry-wit
@@ -83,6 +83,24 @@ export DRYWIT_MODULE_URL="https://raw.githubusercontent.com/rydnr/dry-wit/${DRYW
 # env: DRYWIT_MODULE_PATH: Where to download dry-wit modules.
 export DRYWIT_MODULE_PATH="${HOME}/.dry-wit/src/modules"
 
+# fun: BOOTSTRAP.failsafeExitWithError
+# api: private
+# txt: A fail-safe version of exitWithError.
+# opt: label: The error label.
+# opt: message: The error message.
+# use: BOOTSTRAP.failsafeExitWithError UNACCEPTABLE_API_CALL "'name' cannot be empty";
+function BOOTSTRAP.failsafeExitWithError() {
+  local _label="${1}";
+  local _message="${2}";
+
+  if BOOTSTRAP.failsafeIsFunctionDefined "exitWithError"; then
+    exitWithError "${_label}" "${_message}";
+  else
+    echo "${_message}";
+    exit 1;
+  fi
+}
+
 # fun: BOOTSTRAP.failsafeCheckNotEmpty
 # api: private
 # txt: A fail-safe version of checkNotEmpty.
@@ -94,17 +112,17 @@ export DRYWIT_MODULE_PATH="${HOME}/.dry-wit/src/modules"
 function BOOTSTRAP.failsafeCheckNotEmpty() {
   local _name="${1}";
   if [ -z "${_name}" ]; then
-    exitWithError UNACCEPTABLE_API_CALL "'name' (1) cannot be empty when calling ${FUNCNAME[0]}. Review ${FUNCNAME[1]}";
+    BOOTSTRAP.failsafeExitWithError UNACCEPTABLE_API_CALL "'name' (1) cannot be empty when calling ${FUNCNAME[0]}. Review ${FUNCNAME[1]}";
   fi
   local _value="${2}";
 
   if [ -z "${_value}" ]; then
-    exitWithError UNACCEPTABLE_API_CALL "'${_name}' (${_value}) cannot be empty when calling ${FUNCNAME[1]}. Review ${FUNCNAME[2]}";
+    BOOTSTRAP.failsafeExitWithError UNACCEPTABLE_API_CALL "'${_name}' (${_value}) cannot be empty when calling ${FUNCNAME[1]}. Review ${FUNCNAME[2]}";
   fi
 
   local _index="${3}";
   if [ -z "${_index}" ]; then
-    exitWithError UNACCEPTABLE_API_CALL "'index' (3) cannot be empty when calling ${FUNCNAME[0]}. Review ${FUNCNAME[1]}";
+    BOOTSTRAP.failsafeExitWithError UNACCEPTABLE_API_CALL "'index' (3) cannot be empty when calling ${FUNCNAME[0]}. Review ${FUNCNAME[1]}";
   fi
 }
 
@@ -219,12 +237,10 @@ function BOOTSTRAP.failsafeArrayContains() {
   local -i _rescode=${FALSE};
   local _oldIFS="${IFS}";
 
-  BOOTSTRAP.failsafeCheckNotEmpty "array" "${_array}" 1;
-  BOOTSTRAP.failsafeCheckNotEmpty "item" "${_item}" 2;
-
   IFS="${DWIFS}";
   for _aux in ${_array}; do
     IFS="${_oldIFS}";
+    BOOTSTRAP.failsafeCheckNotEmpty "item" "${_item}" 2;
     if [[ "${_aux}" == "${_item}" ]]; then
       _rescode=${TRUE};
       break;
@@ -335,6 +351,7 @@ if    endsWith "${SCRIPT_NAME}" "-tests.sh" \
    || endsWith "${SCRIPT_NAME}" "-test.sh"; then
   source $(which dry-wit-test) "${SCRIPT_NAME}" $@;
 fi
+
 DRYWIT.main "${SCRIPT_NAME}" $@;
 
 cleanup;
